export const FETCH_USERS = 'user/FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'user/FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'user/FETCH_USERS_ERROR';

export const SELECT_USER = 'user/SELECT_USER';

export const FETCH_USER_DETAILS = 'user/FETCH_USER_DETAILS';
export const FETCH_USER_DETAILS_SUCCESS = 'user/FETCH_USER_DETAILS_SUCCESS';
export const FETCH_USER_DETAILS_ERROR = 'user/FETCH_USER_DETAILS_ERROR';

export const TOGGLE_CURRENT_USER_FAV = 'user/TOGGLE_USER_FAV';
export const TOGGLE_CURRENT_USER_FAV_SUCCESS = 'user/TOGGLE_USER_FAV_SUCCESS';
export const TOGGLE_CURRENT_USER_FAV_ERROR = 'user/TOGGLE_USER_FAV_ERROR';
